apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stihibi
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /myprometheus
  kafka:
    pool: {{ kafka_pool }}
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - secret: pam-stihibi-credentials
      mountPath: /var/run/secrets/credentials/pam-stihibi
  env:
    - name: ADLISTENER_GROUP_ID
      value: "{{ adlistener_group_id }}"
    - name: ADLISTENER_TOPIC
      value: "{{ adlistener_topic }}"
    - name: ADLISTENER_ENABLED
      value: "{{ adlistener_enabled }}"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/run/secrets/credentials/pam-stihibi/secret"
    - name: GOOGLE_CLOUD_PROJECT
      value: "{{ google_cloud_project }}"
